name: maya_public
channels:
- defaults
dependencies:
- mkl=2017.0.1=0
- openssl=1.0.2l=0
- pip=9.0.1=py36_1
- python=3.6.0=0
- readline=6.2=2
- setuptools=27.2.0=py36_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py36_0
- xz=5.2.2=1
- zlib=1.2.8=3
- pip:
  - appnope==0.1.0
  - astroid==1.5.3
  - bleach==1.5.0
  - botocore==1.7.4
  - colorama==0.3.7
  - common==0.1.2
  - cycler==0.10.0
  - decorator==4.0.11
  - docopt==0.6.2
  - docutils==0.14
  - flake8==3.4.1
  - flake8-docstrings==1.1.0
  - flake8-polyfill==1.0.1
  - future==0.16.0
  - git-pylint-commit-hook==2.2.2
  - grpcio==1.6.3
  - grpcio-tools==1.6.3
  - html5lib==0.9999999
  - ipdb==0.10.3
  - ipython==6.1.0
  - ipython-genutils==0.2.0
  - isort==4.2.15
  - jedi==0.11.0
  - jmespath==0.9.3
  - lazy-object-proxy==1.3.1
  - markdown==2.6.9
  - matplotlib==2.0.2
  - mccabe==0.6.1
  - nanomsg==1.0
  - numpy==1.13.1
  - olefile==0.44
  - parso==0.1.0
  - pexpect==4.2.1
  - pickleshare==0.7.4
  - pillow==4.3.0
  - prompt-toolkit==1.0.15
  - protobuf==3.4.0
  - ptyprocess==0.5.2
  - pyasn1==0.3.3
  - pycodestyle==2.3.1
  - pydocstyle==2.1.1
  - pyflakes==1.5.0
  - pygments==2.2.0
  - pylint==1.7.4
  - pyparsing==2.2.0
  - python-dateutil==2.6.0
  - pytz==2017.2
  - pyyaml==3.12
  - rsa==3.4.2
  - s3transfer==0.1.11
  - shapely==1.6.0
  - simplegeneric==0.8.1
  - six==1.11.0
  - snowballstemmer==1.2.1
  - tensorflow==1.3.0
  - tensorflow-tensorboard==0.1.5
  - traitlets==4.3.2
  - wcwidth==0.1.7
  - werkzeug==0.12.2
  - wrapt==1.10.11

